"""migrate_message

Revision ID: 38ffb379f09d
Revises: c0afbae9a926
Create Date: 2021-02-03 22:24:50.993714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ffb379f09d'
down_revision = 'c0afbae9a926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'employees', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'employees', ['recipient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # ### end Alembic commands ###
