"""add message

Revision ID: 6912b08dfa43
Revises: ed080dd3ae0f
Create Date: 2021-01-25 21:23:58.488915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6912b08dfa43'
down_revision = 'ed080dd3ae0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
