"""Create message

Revision ID: d789d0cf0dec
Revises: accbb0722179
Create Date: 2021-01-25 21:15:06.488043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd789d0cf0dec'
down_revision = 'accbb0722179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
