"""Create message

Revision ID: ed080dd3ae0f
Revises: d789d0cf0dec
Create Date: 2021-01-25 21:19:38.635690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed080dd3ae0f'
down_revision = 'd789d0cf0dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
