from .base import BaseEndpoint
from .employees.create import CreateEmployeeEndpoint
from .employees.auth import AuthEmployeeEndpoint
from .employees.employee import EmployeeEndpoint
from .employees.get_all import AllEmployeeEndpoint
from .messages.create import CreateMessageEndpoint
from .messages.message import MessageEndpoint
from .messages.get_all import AllMessageEndpoint
from .health import HealthEndpoint
